export default {
    LOGIN:'LOGIN',
    CLEARE_REDUX_STATE:'CLEARE_REDUX_STATE',
    ITEMS:'ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM:'DELETE_ITEM',   
    LOGOUT: 'LOGOUT',
    UPDATE_LIST : 'UPDATE_LIST'
}