export default {
    LOGIN:'LOGIN',
    CLEAR_REDUX_STATE:'CLEAR_REDUX_STATE',
    ITEMS:'ITEMS',
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM:'DELETE_ITEM',   
    LOGOUT: 'LOGOUT',
    UPDATE_LIST : 'UPDATE_LIST',
    NO_INTERNET:"NO_INTERNET",
}